### PR TITLE
refixed parsing of constant with comment between size and value

### PR DESCRIPTION
**Pull request by zeldin**
The code to handle comments between size and value in constants by arbitrarily concatenating two TOK_CONSTVAL which was introduced in ee8ad72fd950e1ee204e5c97155a50b8b1445dec has three problems:

* It accepts invalid code; e.g. the expression `12'h4 /*foo*/'b0` is accepted as the hexadecimal constant `12'h4b0` despite being syntactically incorrect
* It generates misleading diagnostics; e.g. the expression `a == 1'b0? 1'b1 : 1'b0`
  yields the diagnostic "Digit larger than 1 used in in base-2 constant" (issue #1745)
* It is incomplete - It does not accept any spaces between the comment and the `'`, and no comments between the base and the digits even though spaces are allowed there.

This PR fixes all three problems by making the three parts of a based constant (size, base, digits) into three separate tokens, allowing the linear whitespace (including comments) between them to be treated as normal inter-token whitespace.

### CODE REVIEW

**Comment by eddiehung** [comment]
Thanks for the patch! Can you add tests for all three of those bullet points please?

**Comment by eddiehung** [comment]
And just to be clear, this doesn't "fix" the parsing of `a == 1'b0? 1'b1 : 1'b0` by interpreting the '?' as a ternary operator, but now gives a more relevant error message:

`top.v:2: ERROR: syntax error, unexpected OP_EQ, expecting TOK_PACKAGESEP or '=' or '.' or '['`

**Comment by zeldin** [comment]
@eddiehung I'm unclear how to add a test that something should give an error (two of the three bullet points).  Is there an earlier test of that type I could use for reference?

I could add a test for `4 /*foo*/ 'baa` (with a space before the `'`) which was broken before.  I can't add a test for `4'b /*foo*/ aa` though since the test system tries to compare the result against iverilog which can't handle that expression...

**Comment by zeldin** [comment]
@eddiehung BTW, what is your `top.v`?  The expected error (and the one I'm getting) for that expression is "ERROR: syntax error, unexpected TOK_CONSTVAL" (where the TOK_CONSTVAL is the `1` immediately following the `?`).

**Comment by eddiehung** [comment]
> @eddiehung I'm unclear how to add a test that something should give an error (two of the three bullet points). Is there an earlier test of that type I could use for reference?

Check out the new `logger` pass added recently: https://github.com/YosysHQ/yosys/pull/1705
Be careful about a CI breakage on gcc-4.8 that could result from using this, due to a broken regex implementation: https://github.com/YosysHQ/yosys/pull/1754#issuecomment-597914630

> @eddiehung BTW, what is your top.v? The expected error (and the one I'm getting) for that expression is "ERROR: syntax error, unexpected TOK_CONSTVAL" (where the TOK_CONSTVAL is the 1 immediately following the ?).

2647fe2e4 + `zeldin:constant_with_comment_redux`

`./yosys ../master/top.v` on
```
module top(output a);
assign a == 1'b0? 1'b1 : 1'b0;
endmodule
```
gives:
```
../master/top.v:2: ERROR: syntax error, unexpected OP_EQ, expecting TOK_PACKAGESEP or '=' or '.' or '['
```

**Comment by zeldin** [comment]
I added tests for all three bullet points.

**Comment by mmicko** [comment]
@zeldin  Ah we have problematic case. Please just try running :+1: 
./yosys techlibs/common/gate2lut.v -DLUT_WIDTH=4
Noticed this when running yosys-tests

**Comment by zeldin** [comment]
@mmicko That file has a legitimate syntax error in it.  The first digit is _not_ allowed to be an `_`.
Just replace the `_`  with an actual space and everything is fine.

**Comment by mmicko** [comment]
yeah, understand that, just need to double check with standard

**Comment by mmicko** [comment]
It was invalid so fixed in https://github.com/YosysHQ/yosys/commit/acb341745d436987ad764c9198ff0c6ab63c572c
