### ISSUE TITLE
[regression] defparam failing with default_nettype none

### ISSUE THREAD

**Issue by daveshah1** [YosysHQ/yosys#826]
Testcase:
```
`default_nettype none

module A;
parameter P = 0;
endmodule

module top;
A inst_i();
defparam inst_i.P = 1;
endmodule
```

Regression bisected to commit 23148ffae14318bb34cb311eb13494e25ebf4593

**Comment by adumont** [comment]
Hi. My project passed building (synthesizing) last week just fine (https://travis-ci.org/adumont/hrm-cpu/builds/494525894), it was using yosys at commit e45f62b0c56717a23099425f078d1e56212aa632. 

Today, at Yosys commit  c521f4632f1c82b48a5538c832980668044e8fd9, my same code is failing to synthesize with error: 

`hrmcpu.v:146: ERROR: Identifier `\program0.PROGRAM' is implicitly declared and `default_nettype is set to none.`

Offending line in my code according to yosys is: https://github.com/adumont/hrm-cpu/blob/master/verilog/hrmcpu.v#L146:

`defparam program0.PROGRAM = PROGRAM;`

Changing to PROG #(.PROGRAM(PROGRAM)) program0 (...) seems to work as a workaround.

--

confirmed, synthesis goes well with yosys @ 974927ad (previous commit), then fails with yosys @ 23148ffa.

**Comment by cliffordwolf** [comment]
Ooops. Fixed in 1816fe0.

**Comment by adumont** [comment]
Fix confirmed, working now

https://travis-ci.org/adumont/hrm-cpu/builds/497851251

Thanks a lot
