### ISSUE TITLE
Regression: "ERROR: Don't know how to detect sign and width for AST_AUTOWIRE node!"

### ISSUE THREAD

**Issue by spth** [YosysHQ/yosys#5797]
### Version

Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, g++ 15.2.0-15 -fPIC -O3)

### On which OS did this happen?

Linux

### Reproduction Steps

On my Debian GNU/LInux testing on aarch64 system, I invoke:

/home/philipp/yosys-0.63/yosys -l icesynth2.yosyslog -p "read_verilog -sv cpu2_nosv.v; synth_ice40 -top cpu -json icesynth2.json"

[cpu2_nosv.v.gz](https://github.com/user-attachments/files/26579661/cpu2_nosv.v.gz)

### Expected Behavior

Synthesis. This worked for me in yosys 0.59.1 (I have not yet tried yosys version in between 0.59.1 and 0.63, nor did I try on amd64)

### Actual Behavior

Error:

~~~~
[…]
verilog-ast>       AST_CONSTANT <cpu2_nosv.v:1228.21-1228.24> [0xaaab18ef72e0] bits='00000000000000000000000000000001'(32) basic_prep range=[31:0] int=1 in_param
verilog-ast>     AST_RANGE <cpu2_nosv.v:467.9-467.15> [0xaaab18ef6ed0] basic_prep range=[15:0] in_param
verilog-ast>       AST_CONSTANT <cpu2_nosv.v:467.10-467.12> [0xaaab18ef7000] bits='00000000000000000000000000001111'(32) signed basic_prep range=[31:0] int=15 in_param
verilog-ast>       AST_CONSTANT <cpu2_nosv.v:467.13-467.14> [0xaaab18ef7160] bits='00000000000000000000000000000000'(32) signed basic_prep range=[31:0] in_param
cpu2_nosv.v:1260: ERROR: Don't know how to detect sign and width for AST_AUTOWIRE node!
~~~~

**Comment by spth** [comment]
Looks like a regression between 0.61 and 0.62 to me: I can reproduce the issue on that system using yosys 0.62, 0.63 and  0.64, but not using yosys 0.59.1 and 0.61.

**Comment by Ravenslofty** [comment]
Bisected this to #4235.

**Comment by widlarizer** [comment]
You're using a `OPCODE_LDW_Y_Z` constant which is undefined. It's the only `OPCODE_`-prefixed constant you have. `nosv` makes it sound like you're using `sv2v`, make sure that's doing its job properly.
In the meantime, "properly" meant emitting `g/cpu2_nosv-original.v:1260: Warning: Identifier `\OPCODE_LDW_Y_Z' is implicitly declared.` and then I guess synthesizing as if it was set to 0, which sucked, too. Note that Yosys warnings are usually pretty severe and should really be checked.

**Comment by spth** [comment]
Yes. My Verilog is faulty, which makes this issue less serious than if yosys failed on correct input.

**Comment by widlarizer** [comment]
I think an error is appropriate and a neater error message would be better but the source location does tell you where something is wrong so I'm adjusting it to a feature request (improving the error message to be more helpful) and probably not working on it in the near future
