### ISSUE TITLE
Can't put assert inside case statement

### ISSUE THREAD

**Issue by Edgeworth** [YosysHQ/yosys#862]
## Steps to reproduce the issue
test.v
```
module test(input wire A);
  localparam TEST = 1;
  always_comb begin
    case (A)
      TEST: assert(1);
    endcase
  end
endmodule
```
Repro command:
`yosys -p 'read -sv test.v'`

## Expected behavior
Output:
```
Parsing SystemVerilog input from `test.v' to AST representation.
Generating RTLIL representation for module `\test'.
Successfully finished Verilog frontend.
```

## Actual behavior
Fails to parse.
Output:
```
Parsing SystemVerilog input from `test.v' to AST representation.
test.v:5: ERROR: syntax error, unexpected TOK_ASSERT
```

Reverting e7a34d3  #699  seems to fix this.

**Comment by cliffordwolf** [comment]
Oops! #864 should fix it. Can someone double-check I didn't break anything else this time around?  ;)
