### ISSUE TITLE
Failure to compile 0.57 on macOS

### ISSUE THREAD

**Issue by fxcoudert** [YosysHQ/yosys#5326]
### Version

0.57

### On which OS did this happen?

macOS

### Reproduction Steps

Compile on macOS 13 x86_64 with `make install PREFIX=/usr/local/Cellar/yosys/0.57 PRETTY=0`.

### Expected Behavior

Should compile fine.

### Actual Behavior

Build fails with:

```
  /private/tmp/yosys-20250904-5092-su2ggt/abc/depends.sh "clang++" `dirname src/bdd/llb/llb4Image.c` -g -O -I/private/tmp/yosys-20250904-5092-su2ggt/abc/src -Wall -Wno-unused-function -Wno-write-strings -Wno-sign-compare -DABC_USE_STDINT_H  -DABC_NAMESPACE=abc -fpermissive -x c++ -DABC_USE_CUDD=1 -DABC_USE_READLINE  -DABC_USE_PTHREADS -Wno-unused-but-set-variable src/bdd/llb/llb4Image.c > src/bdd/llb/llb4Image.d
  In file included from frontends/verilog/verilog_parser.y:129:
  ./frontends/verilog/verilog_lexer.h:39:43: error: non-virtual member function marked 'override' hides virtual member function
                  int LexerInput(char* buf, int max_size) override {
                                                          ^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/FlexLexer.h:148:18: note: hidden overloaded virtual function 'frontend_verilog_yyFlexLexer::LexerInput' declared here: type mismatch at 2nd parameter ('size_t' (aka 'unsigned long') vs 'int')
    virtual size_t LexerInput( char* buf, size_t max_size );
                   ^
```

I think this was introduced by https://github.com/YosysHQ/yosys/pull/5135

**Comment by widlarizer** [comment]
What's your flex version? My `FlexLexer.h` declares `virtual int LexerInput( char* buf, int max_size );`

**Comment by fxcoudert** [comment]
```
$ flex -V          
flex 2.6.4 Apple(flex-35)
```

Their source is here: https://github.com/apple-oss-distributions/flex/blob/main/src/FlexLexer.h

**Comment by widlarizer** [comment]
My MacOS experience can be measure in minutes, not years, but I'm guessing `uses_from_macos "flex"` in the brew formula is at fault. We have only been testing in CI against brew flex which doesn't have the Apple patches that break the build. Either 

- the brew package should use flex from brew
- Yosys should be changed to work around the patches

Any preferences? Any reason to avoid brew flex in a brew package? On MacOS, Yosys has always run on brew AFAIK.

Related issue, caused by a struggle to normalize this signature to size_t across flex distributions I guess: https://github.com/verilator/verilator/issues/5360
Another related issue with another workaround (original site wouldn't load for me): https://web.archive.org/web/20240625121534/https://lists.nongnu.org/archive/html/bug-bison/2021-10/msg00019.html

**Comment by gadfort** [comment]
I'm getting similar issues with:
Ubuntu22, 24 on aarch: https://github.com/siliconcompiler/siliconcompiler/actions/runs/17492894967/job/49686618330, https://github.com/siliconcompiler/siliconcompiler/actions/runs/17492894967/job/49686618329
Ubuntu22, 24 on x86: https://github.com/siliconcompiler/siliconcompiler/actions/runs/17492894967/job/49686618326, https://github.com/siliconcompiler/siliconcompiler/actions/runs/17492894967/job/49686618315

```
2025-09-05T12:27:20.8153017Z #21 543.7 In file included from frontends/verilog/verilog_parser.y:129:
2025-09-05T12:27:20.8153537Z #21 543.7 ./frontends/verilog/verilog_lexer.h:12:10: fatal error: FlexLexer.h: No such file or directory
2025-09-05T12:27:20.8154407Z #21 543.7    12 | #include <FlexLexer.h>
2025-09-05T12:27:20.8154989Z #21 543.7       |          ^~~~~~~~~~~~~
2025-09-05T12:27:20.8155250Z #21 543.7 compilation terminated.
```

Install script: https://github.com/siliconcompiler/siliconcompiler/blob/main/siliconcompiler/toolscripts/ubuntu22/install-yosys.sh

**Comment by widlarizer** [comment]
@gadfort you're missing `libfl-dev`, which has been added to the ubuntu requirements example in the README. I should have made sure this is mentioned in the release notes I think, sorry about that

**Comment by gadfort** [comment]
@widlarizer thanks, yes, that works.

**Comment by chenrui333** [comment]
fyi, using brewed flex fixed the build issue for macos 

can be closed via https://github.com/Homebrew/homebrew-core/pull/236117
