### ISSUE TITLE
trigger generated for `always @*` in `write_verilog` is broken if a wire named `initial` already exists

### ISSUE THREAD

**Issue by rroohhh** [YosysHQ/yosys#2914]
Converting the following rtlil snippet to verilog 
```
attribute \top 1
module \top
  wire width 1 input 0 \initial
  wire width 1 input 1 \rst
  wire width 1 input 2 \clk
  wire width 1 \output
  wire width 1 \output$next
  process $group_0
    assign \output$next \output
    assign \output$next \initial
    switch \rst
      case 1'1
        assign \output$next 1'0
    end
    sync init
      update \output 1'0
    sync posedge \clk
      update \output \output$next
  end
end
```
using 
`yosys test.il -p "write_verilog test.v"`

Generates a invalid verilog file:
```verilog
(* top =  1  *)
module top(rst, clk, \initial );
  reg \initial  = 0;
  input clk;
  input \initial ;
  reg \output ;
  reg \output$next ;
  input rst;
  always @* begin
    if (\initial ) begin end
    \output$next  = \output ;
    \output$next  = \initial ;
    casez (rst)
      1'h1:
          \output$next  = 1'h0;
    endcase
  end
  initial begin
      \output  <= 1'h0;
  end
  always @(posedge clk) begin
      \output  <= \output$next ;
  end
endmodule
```
which even yosys itself cannot parse:
```
-- Parsing `test.v' using frontend `verilog' --

1. Executing Verilog-2005 frontend: test.v
Parsing Verilog input from `test.v' to AST representation.
test.v:5: ERROR: Module port `\initial' is neither input nor output.
```

(This seems to have been introduced in #2273)
