### ISSUE TITLE
Fails to parse `initial if (0) $error`

### ISSUE THREAD

**Issue by eddiehung** [YosysHQ/yosys#1084]
## Steps to reproduce the issue

`./yosys system.v` on a91ea661; regression from f01a61f (before PR #1077)

```
module top;
initial
   if (0) $error("ASDF");
endmodule
```

## Expected behavior

No parser error, as on f01a61f.

## Actual behavior

```
-- Parsing `system.v' using frontend `verilog' --

1. Executing Verilog-2005 frontend: system.v
Parsing Verilog input from `system.v' to AST representation.
system.v:3: ERROR: syntax error, unexpected TOK_ELAB_TASK
```

**Comment by udif** [comment]
An effort to fix my mess is in #1086 .
@cliffordwolf , I haven't had to the time yet to check if your changes to my initial PR have addressed the  comments you left on the original PR.
Have your modification addressed those issues, or do I need to put in some more work there?
